name: Question
description: Please use this form if you expect that your issue is rather a question than a problem with the code.
labels: ["question"]
body:
- type: textarea
  id: question
  attributes:
    label: Question
    description: Please provide details on your issue or question.